using System.Globalization;
using System.Security;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using VintageStoryModKit.Settings;

namespace VintageStoryModKit.Build;

internal static class SettingsTypes
{
    public static void ValidateNames(string @namespace, string typeName)
    {
        if (string.IsNullOrWhiteSpace(@namespace))
        {
            throw new ArgumentException(
                "The settings namespace is empty. Set VsmkSettingsNamespace or RootNamespace."
            );
        }

        RequireIdentifier(typeName, "The settings type name");
    }

    public static string Generate(SettingsSchema schema, string @namespace, string typeName)
    {
        ArgumentNullException.ThrowIfNull(schema);

        var code = new StringBuilder();
        code.AppendLine("// <auto-generated/>");
        code.AppendLine("#nullable enable");
        code.AppendLine();
        code.AppendLine(CultureInfo.InvariantCulture, $"namespace {@namespace};");
        code.AppendLine();
        WriteRecord(code, schema.Document, typeName, "$", 0, true);
        return code.ToString();
    }

    private static void WriteRecord(
        StringBuilder code,
        JsonObject schema,
        string typeName,
        string path,
        int depth,
        bool defaulted
    )
    {
        string indent = new string(' ', depth * 4);
        WriteSummary(code, schema, indent);
        code.AppendLine(CultureInfo.InvariantCulture, $"{indent}public sealed record {typeName}");
        code.AppendLine(CultureInfo.InvariantCulture, $"{indent}{{");

        var members = new HashSet<string>(StringComparer.Ordinal) { typeName };
        var nested = new List<Nested>();
        var required = (schema["required"] as JsonArray ?? [])
            .Select(item => item?.GetValue<string>())
            .ToHashSet(StringComparer.Ordinal);
        bool first = true;
        foreach ((string name, JsonNode? node) in Properties(schema))
        {
            var propertySchema = (JsonObject)node!;
            string propertyPath = $"{path}.properties[{JsonSerializer.Serialize(name)}]";
            string identifier = ToIdentifier(name, propertyPath);
            string type = MapType(
                propertySchema,
                identifier,
                identifier + "Settings",
                propertyPath,
                defaulted,
                nested
            );
            if (!members.Add(identifier))
            {
                throw new ArgumentException(
                    $"{propertyPath} maps to C# member '{identifier}', which is already used in {typeName}."
                );
            }

            if (!first)
            {
                code.AppendLine();
            }

            first = false;
            WriteSummary(code, propertySchema, indent + "    ");
            code.AppendLine(
                CultureInfo.InvariantCulture,
                $"{indent}    [global::System.Text.Json.Serialization.JsonPropertyName({JsonSerializer.Serialize(name)})]"
            );
            // Defaults fill only the properties chain, so other members may be absent from valid files.
            // Saving writes absent members back as absent, because the schema may reject null.
            bool optional = !defaulted && !required.Contains(name);
            if (optional)
            {
                code.AppendLine(
                    CultureInfo.InvariantCulture,
                    $"{indent}    [global::System.Text.Json.Serialization.JsonIgnore(Condition = global::System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]"
                );
            }

            string member =
                !optional ? $"required {type}"
                : type.EndsWith('?') ? type
                : type + "?";
            code.AppendLine(
                CultureInfo.InvariantCulture,
                $"{indent}    public {member} {identifier} {{ get; init; }}"
            );
        }

        foreach (
            (
                JsonObject nestedSchema,
                string nestedName,
                string nestedPath,
                bool nestedDefaulted
            ) in nested
        )
        {
            if (!members.Add(nestedName))
            {
                throw new ArgumentException(
                    $"{nestedPath} maps to C# type '{nestedName}', which is already used in {typeName}."
                );
            }

            code.AppendLine();
            WriteRecord(code, nestedSchema, nestedName, nestedPath, depth + 1, nestedDefaulted);
        }

        code.AppendLine(CultureInfo.InvariantCulture, $"{indent}}}");
    }

    private static string MapType(
        JsonObject schema,
        string baseName,
        string objectTypeName,
        string path,
        bool defaulted,
        List<Nested> nested
    )
    {
        List<string> types = TypeNames(schema);
        bool nullable = types.Remove("null");
        if (types.Count == 0 && schema.ContainsKey("properties"))
        {
            types.Add("object");
        }

        if (types.Count != 1)
        {
            return "global::System.Text.Json.Nodes.JsonNode?";
        }

        string? type = types[0] switch
        {
            "boolean" => "bool",
            "integer" => FitsInt32(schema) ? "int" : "long",
            "number" => "double",
            "string" => "string",
            "object" when schema.ContainsKey("properties") => AddNested(
                new Nested(schema, objectTypeName, path, defaulted),
                nested
            ),
            "object" when schema["additionalProperties"] is JsonObject values =>
                $"global::System.Collections.Generic.IReadOnlyDictionary<string, {MapType(values, baseName + "Value", baseName + "Value", $"{path}.additionalProperties", false, nested)}>",
            "array" when schema["items"] is JsonObject items =>
                $"global::System.Collections.Generic.IReadOnlyList<{MapType(items, baseName + "Item", baseName + "Item", $"{path}.items", false, nested)}>",
            _ => null,
        };
        if (type is null)
        {
            return "global::System.Text.Json.Nodes.JsonNode?";
        }

        return nullable ? type + "?" : type;
    }

    private static string AddNested(Nested record, List<Nested> nested)
    {
        nested.Add(record);
        return record.Name;
    }

    private static List<string> TypeNames(JsonObject schema) =>
        schema["type"] switch
        {
            JsonValue value when value.TryGetValue(out string? name) => [name],
            JsonArray array => array
                .Select(item =>
                    item is JsonValue value && value.TryGetValue(out string? name) ? name : ""
                )
                .ToList(),
            _ => [],
        };

    private static bool FitsInt32(JsonObject schema) =>
        IsWithinInt32(schema["minimum"] ?? schema["exclusiveMinimum"])
        && IsWithinInt32(schema["maximum"] ?? schema["exclusiveMaximum"]);

    private static bool IsWithinInt32(JsonNode? bound) =>
        bound is JsonValue value
        && value.TryGetValue(out double number)
        && number >= int.MinValue
        && number <= int.MaxValue;

    private static JsonObject Properties(JsonObject schema) =>
        schema["properties"] as JsonObject ?? [];

    private static string ToIdentifier(string name, string path)
    {
        var identifier = new StringBuilder();
        foreach (
            string part in name.Split(
                name.Where(character => !char.IsLetterOrDigit(character)).Distinct().ToArray(),
                StringSplitOptions.RemoveEmptyEntries
            )
        )
        {
            identifier.Append(char.ToUpperInvariant(part[0]));
            identifier.Append(part.AsSpan(1));
        }
        if (identifier.Length == 0)
        {
            throw new ArgumentException($"{path} has no letters or digits for a C# member name.");
        }

        if (char.IsDigit(identifier[0]))
        {
            identifier.Insert(0, '_');
        }

        return identifier.ToString();
    }

    private static void RequireIdentifier(string value, string description)
    {
        if (
            string.IsNullOrEmpty(value)
            || !(char.IsLetter(value[0]) || value[0] == '_')
            || !value.All(character => char.IsLetterOrDigit(character) || character == '_')
        )
        {
            throw new ArgumentException($"{description} '{value}' is not a C# identifier.");
        }
    }

    private static void WriteSummary(StringBuilder code, JsonObject schema, string indent)
    {
        string? text =
            (schema["description"] ?? schema["title"]) is JsonValue value
            && value.TryGetValue(out string? summary)
                ? summary
                : null;
        if (string.IsNullOrWhiteSpace(text))
        {
            return;
        }

        code.AppendLine(CultureInfo.InvariantCulture, $"{indent}/// <summary>");
        foreach (string line in text.Split('\n'))
        {
            code.AppendLine(
                CultureInfo.InvariantCulture,
                $"{indent}/// {SecurityElement.Escape(line.TrimEnd('\r'))}"
            );
        }

        code.AppendLine(CultureInfo.InvariantCulture, $"{indent}/// </summary>");
    }

    private sealed record Nested(JsonObject Schema, string Name, string Path, bool Defaulted);
}
