<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RollForward>Major</RollForward>
    <Description>Build and staging tools for Vintage Story mods.</Description>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);_VsmkPackTool</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../VintageStoryModKit.Settings.Core/VintageStoryModKit.Settings.Core.csproj" />
    <PackageReference Include="ILRepack" Version="2.0.48" GeneratePathProperty="true" />
    <InternalsVisibleTo Include="VintageStoryModKit.Tests" />
    <None
      Include="$(PkgILRepack)/tools/ILRepack.exe;$(PkgILRepack)/tools/ILRepack.runtimeconfig.json"
      Link="ilrepack/%(Filename)%(Extension)"
      CopyToOutputDirectory="PreserveNewest"
      Visible="false"
    />
    <None
      Include="buildTransitive/**"
      Pack="true"
      PackagePath="buildTransitive/%(RecursiveDir)%(Filename)%(Extension)"
    />
    <None Include="../../licenses/*.txt" Pack="true" PackagePath="licenses/" />
  </ItemGroup>
  <Target Name="_VsmkPackTool">
    <ItemGroup>
      <TfmSpecificPackageFile
        Include="$(OutDir)*.dll;$(OutDir)*.deps.json;$(OutDir)*.runtimeconfig.json"
        PackagePath="tools/$(TargetFramework)/"
      />
      <TfmSpecificPackageFile
        Include="$(OutDir)ilrepack/*"
        PackagePath="tools/$(TargetFramework)/ilrepack/"
      />
    </ItemGroup>
  </Target>
</Project>
