rule("test")
on_load(function(target)
    target:set("kind", "phony")
    target:set("default", false)
    target:data_set("vsmk.test", target:extraconf("rules", "@addon/vsmk/test") or {})
    target:add("tests", "dotnet")
end)
on_test(function(target)
    return import("@self.test").run(target)
end)
